// Code generated by protoc-gen-go. DO NOT EDIT.
// source: role.proto

package roles

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Roles int32

const (
	Roles_ADMINISTRATOR Roles = 0
	Roles_LEADER        Roles = 1
	Roles_USER          Roles = 2
)

var Roles_name = map[int32]string{
	0: "ADMINISTRATOR",
	1: "LEADER",
	2: "USER",
}

var Roles_value = map[string]int32{
	"ADMINISTRATOR": 0,
	"LEADER":        1,
	"USER":          2,
}

func (x Roles) String() string {
	return proto.EnumName(Roles_name, int32(x))
}

func (Roles) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_48a3ff9f7c9032f8, []int{0}
}

func init() {
	proto.RegisterEnum("roles.Roles", Roles_name, Roles_value)
}

func init() { proto.RegisterFile("role.proto", fileDescriptor_48a3ff9f7c9032f8) }

var fileDescriptor_48a3ff9f7c9032f8 = []byte{
	// 94 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0xca, 0xcf, 0x49,
	0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0xb1, 0x8b, 0xb5, 0x0c, 0xb8, 0x58, 0x83,
	0x40, 0x0c, 0x21, 0x41, 0x2e, 0x5e, 0x47, 0x17, 0x5f, 0x4f, 0x3f, 0xcf, 0xe0, 0x90, 0x20, 0xc7,
	0x10, 0xff, 0x20, 0x01, 0x06, 0x21, 0x2e, 0x2e, 0x36, 0x1f, 0x57, 0x47, 0x17, 0xd7, 0x20, 0x01,
	0x46, 0x21, 0x0e, 0x2e, 0x96, 0xd0, 0x60, 0xd7, 0x20, 0x01, 0xa6, 0x24, 0x36, 0xb0, 0x7e, 0x63,
	0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xa4, 0x05, 0x0e, 0xb4, 0x4d, 0x00, 0x00, 0x00,
}
