// Code generated by mockery v2.32.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	database "github.com/quocbang/api-server-basic/database"
)

// DataManager is an autogenerated mock type for the DataManager type
type DataManager struct {
	*mock.Mock
}

// Close provides a mock function with given fields:
func (_m *DataManager) Close() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Tasks provides a mock function with given fields:
func (_m *DataManager) Tasks() database.Tasks {
	ret := _m.Called()

	var r0 database.Tasks
	if rf, ok := ret.Get(0).(func() database.Tasks); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(database.Tasks)
		}
	}

	return r0
}

// Users provides a mock function with given fields:
func (_m *DataManager) Users() database.Users {
	ret := _m.Called()

	var r0 database.Users
	if rf, ok := ret.Get(0).(func() database.Users); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(database.Users)
		}
	}

	return r0
}

// NewDataManager creates a new instance of DataManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDataManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *DataManager {
	mock := &DataManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
